export const todaysScoreBoard = {
  __typename: "TodaysScoreBoard",
  gameDate: "2022-04-24",
  leagueId: "00",
  leagueName: "National Basketball Association",
  games: [
    {
      __typename: "Game",
      gameId: "0042100144",
      gameCode: "20220424/PHXNOP",
      gameStatus: 2,
      gameStatusText: "Q1 02:09",
      period: 1,
      gameClock: "PT02M09.00S",
      gameTimeUTC: "2022-04-25T01:30:00Z",
      regulationPeriods: 4,
      ifNecessary: false,
      gameEt: "2022-04-24T21:30:00-04:00",
      seriesGameNumber: "Game 4",
      seriesText: "PHX leads series 2-1",
      homeTeam: {
        __typename: "Team",
        periods: [
          {
            __typename: "Period",
            score: 21,
            periodType: "REGULAR",
            period: 1,
          },
          {
            __typename: "Period",
            score: 0,
            periodType: "REGULAR",
            period: 2,
          },
          {
            __typename: "Period",
            score: 0,
            periodType: "REGULAR",
            period: 3,
          },
          {
            __typename: "Period",
            score: 0,
            periodType: "REGULAR",
            period: 4,
          },
        ],
        teamId: 1610612740,
        teamName: "Pelicans",
        teamCity: "New Orleans",
        wins: 1,
        losses: 2,
        teamTricode: "NOP",
        score: 21,
        seed: 8,
        inBonus: 0,
        timeoutsRemaining: 6,
      },
      awayTeam: {
        __typename: "Team",
        periods: [
          {
            __typename: "Period",
            score: 18,
            periodType: "REGULAR",
            period: 1,
          },
          {
            __typename: "Period",
            score: 0,
            periodType: "REGULAR",
            period: 2,
          },
          {
            __typename: "Period",
            score: 0,
            periodType: "REGULAR",
            period: 3,
          },
          {
            __typename: "Period",
            score: 0,
            periodType: "REGULAR",
            period: 4,
          },
        ],
        teamName: "Suns",
        teamId: 1610612756,
        teamCity: "Phoenix",
        teamTricode: "PHX",
        wins: 2,
        losses: 1,
        score: 18,
        seed: 1,
        inBonus: 0,
        timeoutsRemaining: 6,
      },
      gameLeaders: {
        __typename: "GameLeaders",
        awayLeaders: {
          __typename: "Player",
          personId: 1629028,
          name: "Deandre Ayton",
          jerseyNum: "22",
          position: "C",
          teamTricode: "PHX",
          playerSlug: "deandre-ayton",
          points: 10,
          rebounds: 2,
          assists: 0,
        },
        homeLeaders: {
          __typename: "Player",
          personId: 1627742,
          name: "Brandon Ingram",
          jerseyNum: "14",
          position: "F",
          teamTricode: "NOP",
          playerSlug: "brandon-ingram",
          rebounds: 0,
          points: 11,
          assists: 1,
        },
      },
      pbOdds: {
        __typename: "PbOdds",
        suspended: 1,
        odds: 0,
        team: null,
      },
    },
    {
      __typename: "Game",
      gameId: "0042100124",
      gameCode: "20220424/MILCHI",
      gameStatus: 3,
      gameStatusText: "Final",
      period: 4,
      gameClock: "",
      gameTimeUTC: "2022-04-24T17:00:00Z",
      regulationPeriods: 4,
      ifNecessary: false,
      gameEt: "2022-04-24T13:00:00Z",
      seriesGameNumber: "Game 4",
      seriesText: "MIL leads series 3-1",
      homeTeam: {
        __typename: "Team",
        periods: [
          {
            __typename: "Period",
            score: 22,
            periodType: "REGULAR",
            period: 1,
          },
          {
            __typename: "Period",
            score: 19,
            periodType: "REGULAR",
            period: 2,
          },
          {
            __typename: "Period",
            score: 33,
            periodType: "REGULAR",
            period: 3,
          },
          {
            __typename: "Period",
            score: 21,
            periodType: "REGULAR",
            period: 4,
          },
        ],
        teamId: 1610612741,
        teamName: "Bulls",
        teamCity: "Chicago",
        wins: 1,
        losses: 3,
        teamTricode: "CHI",
        score: 95,
        seed: 6,
        inBonus: null,
        timeoutsRemaining: 0,
      },
      awayTeam: {
        __typename: "Team",
        periods: [
          {
            __typename: "Period",
            score: 25,
            periodType: "REGULAR",
            period: 1,
          },
          {
            __typename: "Period",
            score: 31,
            periodType: "REGULAR",
            period: 2,
          },
          {
            __typename: "Period",
            score: 34,
            periodType: "REGULAR",
            period: 3,
          },
          {
            __typename: "Period",
            score: 29,
            periodType: "REGULAR",
            period: 4,
          },
        ],
        teamName: "Bucks",
        teamId: 1610612749,
        teamCity: "Milwaukee",
        teamTricode: "MIL",
        wins: 3,
        losses: 1,
        score: 119,
        seed: 3,
        inBonus: null,
        timeoutsRemaining: 1,
      },
      gameLeaders: {
        __typename: "GameLeaders",
        awayLeaders: {
          __typename: "Player",
          personId: 203507,
          name: "Giannis Antetokounmpo",
          jerseyNum: "34",
          position: "F",
          teamTricode: "MIL",
          playerSlug: null,
          points: 32,
          rebounds: 17,
          assists: 7,
        },
        homeLeaders: {
          __typename: "Player",
          personId: 203897,
          name: "Zach LaVine",
          jerseyNum: "8",
          position: "G-F",
          teamTricode: "CHI",
          playerSlug: null,
          rebounds: 5,
          points: 24,
          assists: 13,
        },
      },
      pbOdds: {
        __typename: "PbOdds",
        suspended: 1,
        odds: 0,
        team: null,
      },
    },
    {
      __typename: "Game",
      gameId: "0042100164",
      gameCode: "20220424/GSWDEN",
      gameStatus: 3,
      gameStatusText: "Final",
      period: 4,
      gameClock: "",
      gameTimeUTC: "2022-04-24T19:30:00Z",
      regulationPeriods: 4,
      ifNecessary: false,
      gameEt: "2022-04-24T15:30:00Z",
      seriesGameNumber: "Game 4",
      seriesText: "GSW leads series 3-1",
      homeTeam: {
        __typename: "Team",
        periods: [
          {
            __typename: "Period",
            score: 26,
            periodType: "REGULAR",
            period: 1,
          },
          {
            __typename: "Period",
            score: 37,
            periodType: "REGULAR",
            period: 2,
          },
          {
            __typename: "Period",
            score: 35,
            periodType: "REGULAR",
            period: 3,
          },
          {
            __typename: "Period",
            score: 28,
            periodType: "REGULAR",
            period: 4,
          },
        ],
        teamId: 1610612743,
        teamName: "Nuggets",
        teamCity: "Denver",
        wins: 1,
        losses: 3,
        teamTricode: "DEN",
        score: 126,
        seed: 6,
        inBonus: null,
        timeoutsRemaining: 0,
      },
      awayTeam: {
        __typename: "Team",
        periods: [
          {
            __typename: "Period",
            score: 21,
            periodType: "REGULAR",
            period: 1,
          },
          {
            __typename: "Period",
            score: 31,
            periodType: "REGULAR",
            period: 2,
          },
          {
            __typename: "Period",
            score: 37,
            periodType: "REGULAR",
            period: 3,
          },
          {
            __typename: "Period",
            score: 32,
            periodType: "REGULAR",
            period: 4,
          },
        ],
        teamName: "Warriors",
        teamId: 1610612744,
        teamCity: "Golden State",
        teamTricode: "GSW",
        wins: 3,
        losses: 1,
        score: 121,
        seed: 3,
        inBonus: null,
        timeoutsRemaining: 0,
      },
      gameLeaders: {
        __typename: "GameLeaders",
        awayLeaders: {
          __typename: "Player",
          personId: 201939,
          name: "Stephen Curry",
          jerseyNum: "30",
          position: "G",
          teamTricode: "GSW",
          playerSlug: null,
          points: 33,
          rebounds: 3,
          assists: 8,
        },
        homeLeaders: {
          __typename: "Player",
          personId: 203999,
          name: "Nikola Jokic",
          jerseyNum: "15",
          position: "C",
          teamTricode: "DEN",
          playerSlug: null,
          rebounds: 8,
          points: 37,
          assists: 6,
        },
      },
      pbOdds: {
        __typename: "PbOdds",
        suspended: 1,
        odds: 0,
        team: null,
      },
    },
    {
      __typename: "Game",
      gameId: "0042100104",
      gameCode: "20220424/MIAATL",
      gameStatus: 3,
      gameStatusText: "Final",
      period: 4,
      gameClock: "",
      gameTimeUTC: "2022-04-24T23:00:00Z",
      regulationPeriods: 4,
      ifNecessary: false,
      gameEt: "2022-04-24T19:00:00Z",
      seriesGameNumber: "Game 4",
      seriesText: "MIA leads series 3-1",
      homeTeam: {
        __typename: "Team",
        periods: [
          {
            __typename: "Period",
            score: 26,
            periodType: "REGULAR",
            period: 1,
          },
          {
            __typename: "Period",
            score: 15,
            periodType: "REGULAR",
            period: 2,
          },
          {
            __typename: "Period",
            score: 20,
            periodType: "REGULAR",
            period: 3,
          },
          {
            __typename: "Period",
            score: 25,
            periodType: "REGULAR",
            period: 4,
          },
        ],
        teamId: 1610612737,
        teamName: "Hawks",
        teamCity: "Atlanta",
        wins: 1,
        losses: 3,
        teamTricode: "ATL",
        score: 86,
        seed: 8,
        inBonus: null,
        timeoutsRemaining: 1,
      },
      awayTeam: {
        __typename: "Team",
        periods: [
          {
            __typename: "Period",
            score: 25,
            periodType: "REGULAR",
            period: 1,
          },
          {
            __typename: "Period",
            score: 30,
            periodType: "REGULAR",
            period: 2,
          },
          {
            __typename: "Period",
            score: 25,
            periodType: "REGULAR",
            period: 3,
          },
          {
            __typename: "Period",
            score: 30,
            periodType: "REGULAR",
            period: 4,
          },
        ],
        teamName: "Heat",
        teamId: 1610612748,
        teamCity: "Miami",
        teamTricode: "MIA",
        wins: 3,
        losses: 1,
        score: 110,
        seed: 1,
        inBonus: null,
        timeoutsRemaining: 1,
      },
      gameLeaders: {
        __typename: "GameLeaders",
        awayLeaders: {
          __typename: "Player",
          personId: 202710,
          name: "Jimmy Butler",
          jerseyNum: "22",
          position: "F",
          teamTricode: "MIA",
          playerSlug: null,
          points: 36,
          rebounds: 10,
          assists: 4,
        },
        homeLeaders: {
          __typename: "Player",
          personId: 1629631,
          name: "De'Andre Hunter",
          jerseyNum: "12",
          position: "F-G",
          teamTricode: "ATL",
          playerSlug: null,
          rebounds: 3,
          points: 24,
          assists: 1,
        },
      },
      pbOdds: {
        __typename: "PbOdds",
        suspended: 1,
        odds: 0,
        team: null,
      },
    },
  ],
};
